CREATE DATABASE IF NOT EXISTS LEPONEYFRINGANT;
USE LEPONEYFRINGANT;

CREATE USER IF NOT EXISTS poney@localhost IDENTIFIED BY 'fringant';
GRANT ALL ON LEPONEYFRINGANT.* TO poney@localhost;

CREATE TABLE IF NOT EXISTS utilisateurs (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    pseudo VARCHAR(255) NOT NULL UNIQUE,
    prenom VARCHAR(255) NOT NULL,
    nom VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    numero INT NOT NULL UNIQUE,
    adresse VARCHAR(255)NOT NULL,
    cp INT NOT NULL,
    ville VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE IF NOT EXISTS profils (
    profilID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    titre VARCHAR(255),
    photo VARCHAR(255),
    description TEXT
);

CREATE TABLE IF NOT EXISTS interets ( 
    nom VARCHAR(255)
);

